version: "3"

networks:
  kong-fc:
   external: false

volumes:
  postgres_data:
      driver: local

services:
  app:
    build: .
    container_name: gokeycloack
    volumes:
     - .:/go/src/
    networks:
      - kong-fc
    ports:
      - "8081:8081"
    # extra_hosts:
    #  - "host.docker.internal:172.17.0.1"
  
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloack
      POSTGRES_USER: keycloack
      POSTGRES_PASSWORD: password
    networks:
      - kong-fc
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"

  keycloack:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloack
      DB_USER: keycloack
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    networks:
      - kong-fc
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
